### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by TragedyN** [SishangLi/Skypool_Objection_Detection#2]
url.txt里的链接无法下载数据集，请问有什么其他方式可以下载吗

**Comment by SishangLi** [comment]
链接：https://pan.baidu.com/s/1iAdJbpR9luZKHkcz7-2q2A&nbsp;
提取码：0azj



请勿继续传播，谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SishangLi/Skypool_Objection_Detection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午2:45
收件人:&nbsp;"SishangLi/Skypool_Objection_Detection"<Skypool_Objection_Detection@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[SishangLi/Skypool_Objection_Detection] dataset (#2)





 
url.txt里的链接无法下载数据集，请问有什么其他方式可以下载吗

**Comment by TragedyN** [comment]
感谢
